namespace AfDLehrer
{
    public static class Schule
    {
        /// <summary>
        /// Alle Rechte bei www.schulliste.eu
        /// </summary>
        public static string[] Schulen { get; } =
        {
            "Edith Stein Schule, Grundschule mit schulartunabhängiger Orientierungsstufe in freier Trägerschaft",
            "Freie Montessori Schule MKK",
            "Freie Waldorfschule Marburg",
            "Grundschule Sagard",
            "Montessori Schule Wiesbaden",
            "Stiftung Louisenlund",
            "Dresden International School (Internationale Gesamtschule, Staatlich genehmigte Ersatzschule, anerkannte Ergänzungsschule)",
            "DPFA-Regenbogen-Grundschule/Kindergarten Görlitz",
            "Schule im Emsbachtal",
            "Corona-Schröter-Grundschule  ",
            "Schulzentrum Marienhöhe",
            "Private Ganztagsgrundschule der Privaten Schule IBB gGmbH (Staatlich anerkannte Ersatzschule)",
            "International School Campus - Metropolregion Hamburg",
            "Alteburg-Schule",
            "AWO-Spatzenschule Neukalen, Grundschule in freier Trägerschaft ",
            "Internationale Grundschule Glauchau (Staatlich anerkannte Ersatzschule)",
            "Freie Reformschule Speyer (FRS)",
            "PbG - Private bilinguale Ganztagsschule",
            "Freie Grundschule Quickborn",
            "Bilinguale Grundschule PHORMS Hamburg",
            "Grundschule an der Hasenheide  ",
            "Evangelische Grundschule im Rochlitzer Land (Staatlich anerkannte Ersatzschule)",
            "Grundschule Luruper Hauptstraße",
            "Erich Kästner Grundschule Cottbus ",
            "Torwiesenschule der Diakonie Stetten e.V.",
            "Westerwaldschule",
            "Grundschule Gollmitz  ",
            "element-i Schule im STEP / Freie Grundschule Stuttgart",
            "Franz-Leuninger-Schule",
            "element-i Gemeinschaftsschule Technido Karlsruhe",
            "Montessori Bildungshaus + Monaddrei-Schule Hamburg",
            "Freie Reformschule ",
            "Montessori Schule Idstein",
            "Evangelisch-diakonische Grundschule Löbau (Staatlich anerkannte Ersatzschule)",
            "Evangelische Schule Naila, Private Grundschule und Mittelschule",
            "50. Grundschule Dresden ",
            "Martinus-Schule Grund- und Realschule plus",
            "August-Hermann-Francke-Grundschule (Staatlich anerkannte Ersatzschule)",
            "Metropolitan School Frankfurt",
            "Antonius-von-Padua-Schule",
            "Hans-Fallada-Grundschule  ",
            "Johannes-Schwennesen-Schule ",
            "Sabine-Ball-Schule",
            "Katholische Grundschule und weiterführende Förderklassen ",
            "Freiherr-vom-Stein-Schule Dauborn, Europaschule",
            "Freie Schule Fläming * Ganzheitliche Naturschule nach Maria Montessori",
            "Freie evangelische Schule Ulm e.V. Grundschule",
            "Hans-Böckler-Schule Grund- und Gemeinschaftsschule der Stadt Neumünster",
            "Grundschule Marienthal",
            "Schulzentrum Vetschau",
            "Grundschule St. Remigius Kröv ",
            "Elisabeth-von-Schlieben-Grundschule  ",
            "Grundschule ",
            "Leibniz Privatschule Elmshorn Kindergarten, Grund-, Gemeinschaftsschule, Gymnasium und IB Diploma - internationales ABITUR",
            "Wolfgang-Rosenthal-Grundschule Thallwitz",
            "International Bilingual Montessori School",
            "Sophie-Scholl-Schule",
            "Konrad-Haenisch-Schule",
            "Heinrich-Steinhöwel Gemeinschaftsschule",
            "thuringia international school - weimar  ",
            "Institut für Mathematisches Lernen (IML) Rechenschwäche Dyskalkulie Therapiezentrum (IML)",
            "Montessori Grundschule Königs Wusterhausen der FAW gGmbH",
            "Astrid-Lindgren-Grundschule  ",
            "Kirchbergschule",
            "Grundschule Bonbaden",
            "Schule im Autal Grundschule",
            "Grundschule Am Pekenberg",
            "Grundschule Nieder Seifersdorf",
            "Grundschule Landeck",
            "Regenbogenschule",
            "37. Grundschule Dresden",
            "Schule Hinsbleek",
            "Grundschule Hoheluft",
            "Grundschule Leppersdorf",
            "Grundschule Lichterfelde  ",
            "Grundschule ",
            "Grundschule Innenstadt am Fischmarkt",
            "Matthias-Claudius-Schule",
            "Haslochbergschule",
            "90. Grundschule Dresden",
            "Montessori-Ganztagsgrundschule Kleeblatt",
            "Kids Camp Bilingual Primary School",
            "Freie Christliche Grundschule Hilden (Staatl. anerkannte Ersatzschule)",
            "Montessori-Zentrum Hofheim",
            "Grundschule Nordstadt  ",
            "Leo-Sternberg-Schule",
            "Schule Stengelestraße",
            "Grundschule Auerhammer",
            "Private Immanuel-Schule München des Fördervereins adventistischer Schulen in Bayern e. V.",
            "Internationale Grundschule Potsdam genehmigte Ersatzschule",
            "August-Hermann-Francke-Schule",
            "Erasmus Frankfurter Stadtschule ",
            "Bilinguale Montessori-Schule  ",
            "Mittelpunktschule Wohratal",
            "Lycée Français de Hambourg Antoine de Saint-Exupéry",
            "Freie Christliche Schule Wiesbaden",
            "Friedrich-Wilhelm-Raiffeisen-Schule",
            "Katharina-die-Große-Schule",
            "Dietrich-Heise-Schule Freie Evangelische Grundschule Görlitz (Staatlich anerkannte Ersatzschule)",
            "Evangelisches Schulzentrum Muldental (Staatlich anerkannte Ersatzschule)",
            "Freie Waldorfschule Wernstein",
            "Schkola Oberland¨Freie Schule an der Haine Gymnasium (Staatlich genehmigte Ersatzschule)",
            "Grundschule ",
            "Grundschule Krebeck/ Bodensee",
            "Freie Schule der Region Zingst/Darss/Fischland Prerow, Integrierte Gesamtschule mit Grundschule und gymnasiale Oberstufe in freier Traegerschaft",
            "Schule am See Grundschule des Schulverbandes Groß Wittensee / Holtsee",
            "Wartburg International School Europe: Bilinguale Bildung in Deutschlands grüner Mitte",
            "Walter-Kolb-Schule",
            "Paul-Maar-Schule",
            "DPFA-Regenbogen-Grundschule Chemnitz Staatlich anerkannte Ersatzschule",
            "Grundschule am Baumschulenweg ",
            "Schule Wildschwanbrook",
            "Diesterweggrundschule",
            "Grundschule Eggersdorf  ",
            "St. Georg-Schule  ",
            "Kreuzbergschule",
            "Freie Waldorfschule Wiesbaden",
            "element-i-Schule im Technido, Freie Grundschule und Gemeinschaftsschule",
            "Evangelische Grundschule Gotha ",
            "Lycée Français de Hambourg Antoine de St Exupéry (Grundschule)",
            "Montessori-Grundschule Nordhausen",
            "DPFA-Schulen gemeinnützige GmbH Berufsfachschule für Technik Ersatzschule",
            "Mathildenschule - Verbundene Schule der Stadt Offenbach am Main",
            "Internationale Grundschule Crinitzberg (IGC), Staatlich anerkannte Ersatzschule",
            "International Primary School Stollberg, anerkannte Grundschule",
            "Freie Montessori Schule Main-Kinzig-Kreis",
            "Bugenhagen-Schule (Grundschule )",
            "Evangelische Grundschule ",
            "accadis International School",
            "Textorschule",
            "Evangelische Grundschule Tröbitz anerkannte Ersatzschule ",
            "Fritz-Gansberg-Schule",
            "Joseph-Carlebach-Schule (Vorschule - Grundschule - Stadtteilschule)",
            "Evangelische Grundschule Frankenthal Bekenntnisschule (Staatlich anerkannte Ersatzschule)",
            "Grundschule der Gemeinde Großhartmannsdorf",
            "Schule auf der Rude ",
            "Montessorischule Niederbarnim Grundschule anerkannte Ersatzschule",
            "Mörike-Schule Grund- und Werkrealschule",
            "Grundschule Utkiek ",
            "Schule Eulenkrugstraße",
            "Grundschule Oederan",
            "Gehlsdorfer Grundschule",
            "Ueberauer Schule",
            "Karl-Preising-Schule",
            "Campus Klarenthal",
            "Freie Schule Leben und Lernen ",
            "Grundschule Köllerbach",
            "Grundschule Gebrüder Grimm",
            "Evangelische Montessori-Grundschule Erlbach-Kirchberg (Staatlich anerkannte Ersatzschule)",
            "Grundschule Lößnitz-Neustadt",
            "Adolph-Diesterweg-Schule",
            "Pfarrer-Toni-Sode-Grundschule ",
            "Grundschule Stadtmitte Finsterwalde ",
            "Ulrich-Schiegg-Schule  Gosbach",
            "Berg-Grundschule  ",
            "Freiherr-vom-Stein-Schule - Europaschule Gladenbach",
            "Johann-Heinrich-Bolte-Grundschule Fehrbellin ",
            "Evangelische Grundschule Mogendorf u.N.",
            "Zeppelinschule Speyer ",
            "Evangelische Grundschule Eilenburg CULTUS+ (Staatlich genehmigte Ersatzschule)",
            "Grundschule Binsfeld  ",
            "Johann-Christoph-Blumhardt-Schule Freie evangelische Grund- und Werkrealschule und berufliches Gymna",
            "August-Hermann-Francke-Schule Farmsen",
            "Georg-Müller-Schule",
            "Evangelische Grundschule Bräunsdorf/Limbach-Oberfrohna (Staatlich anerkannte Ersatzschule)",
            "Heinrich-Mumbächer-Schule ",
            "Karl-Treutel-Schule",
            "Johann Heinrich Pestalozzi Grundschule ",
            "Schule Mahndorf ",
            "Grundschule Breklum-Bredstedt, Standort Bredstedt",
            "Evangelische Grundschule St. Katharina (Staatlich anerkannte Ersatzschule)",
            "Schöntalschule ",
            "Altenburgschule",
            "Schule am Schleemer Park",
            "Grundschule Kemeler Heide",
            "Grund- und Gesamtschule Lehnin \"Heinrich Julius Bruns\" ",
            "Albert-Schweitzer-Schule",
            "August-Hermann-Francke-Schule Bahrenfeld",
            "August-Hermann-Francke-Schule Berne",
            "Grundschule Schloßborn",
            "Ganztagsschule Fährstraße",
            "Tümpelgarten-Schule",
            "Libertasschule Löwenberg  Grund- und Oberschule",
            "Schlossbergschule",
            "Grundschule Römerberg",
            "Grundschule am Priesterweg  ",
            "Grundschule am Rippberg Hattenhof",
            "Schule Fünfhausen-Warwisch",
            "Adventschule Oberhavel\" –Oberschule mit anerkanntem Grundschulteil-",
            "Freie Christliche Schule Lüdenscheid -Grundschule-",
            "Grundschule Burgbrohl ",
            "Friedrich-Ludwig-Jahn-Grundschule Lübben  ",
            "Stadtschule Altlandsberg , Oberschule mit Grundschulteil ",
            "Lietz-Internat Hohenwehrda",
            "Grundschule Neundorf",
            "Schule Kapellenweg",
            "Grundschule ",
            "Francke - Spielschule",
            "Grundschule Blumenau",
            "Grundschule Weisenheim am Sand ",
            "3. Schule Grundschule der Stadt Leipzig",
            "IGS Eschersheim",
            "Grundschule John Brinckman",
            "Montessori Rotenburg e.V. Grundschule",
            "Grundschule Beilrode",
            "Grundschule ",
            "19. Grundschule Dresden",
            "102. Grundschule Dresden ",
            "Kirsten Boie Schule, Grundschule der Gemeinde Barsbüttel",
            "Mittelpunktschule Adorf",
            "Grundschule St. Willibrord ",
            "Grundschule Lewitzrand Matzlow",
            "Theodor-Heuss-Schule  ",
            "Waldschule ",
            "Grundschule Fruerlund ",
            "Wiebelsbacher Schule",
            "Schule Grönauer Baum ",
            "Schule Mittlerer Landweg",
            "Grundschule Am Dorfanger  ",
            "Obermayr Europa-Schule",
            "Schule Strom ",
            "Ernst-Born-Schule  ",
            "Merz Schule gGmbH Private Grundschule und Gymnasium",
            "Schulzentrum \"Janusz Korczak\"",
            "Boehleschule",
            "St.-Marien-Schule ",
            "Grundschule Elmshausen",
            "Schule Schulkamp",
            "Grundschule Niederkaufungen",
            "Wilhelm-Busch-Grundschule Zittau",
            "Grundschule Mylau",
            "Grundschule Weddingstedt ",
            "61. Grundschule Dresden ",
            "Evangelische Johannes Schule Langhagen, Grundschule mit schulartunabhängiger Orientierungsstufe in freier Trägerschaft",
            "Heinrich-Heine-Schule",
            "Grundschule \"Lommatzscher Pflege\"",
            "Ludwig-Weber-Schule",
            "Grundschule Naunhof",
            "120. Grundschule \"Am Geberbach\"",
            "Walter-Bernstein-Grundschule Schiffweiler",
            "Grundschule Burgen  ",
            "Grundschule",
            "Grundschule am Ith Coppenbrügge",
            "Christian-Morgenstern-Schule",
            "Grundschule Offheim",
            "Carlo-Mierendorff-Schule",
            "Friedrich-Schiller-Schule Grund- und Werkrealschule",
            "Grundschule Weinhübel",
            "Karl-von-Ibell-Schule",
            "Berlin Brandenburg International School GmbH (BBIS)  ",
            "ASF-Grundschule ",
            "Johann-Wolfgang-von-Goethe-Schule  ",
            "Carl-Orff-Schule",
            "Freie Fröbelschule Rudolstadt/Cumbach",
            "Friedrich-Fröbel-Schule",
            "Grundschule Erich Schindler Wahrenbrück",
            "Grundschule ",
            "Grundschule Bernkastel-Kues  ",
            "Neue Grundschule Marquardt",
            "Grundschule Samuel von Pufendorf ",
            "Kleeblatt-Grundschule Ludwigsfelde ",
            "Ludwig-Erk-Schule",
            "Johann-Esche-Grundschule",
            "Geschwister-Grimm-Schule",
            "Johann-Friedrich-Krause-Schule",
            "Schule Forsmannstraße",
            "Humboldtschule",
            "Freie aktive Schule Auf den Fildern Grund- und Hauptschule mit Werkrealschule",
            "Schule Ramsharde ",
            "Evangelische Grundschule ",
            "Mittelpunktschule Dautphetal",
            "Waldring-Grundschule Wittstock  ",
            "Sorbische Grundschule ",
            "Privatschule Mittelholstein Grundschule & Gymnasium",
            "Grundschule ",
            "Grundschule ",
            "Grundschule Tanneck ",
            "Grundschule Kolkwitz  ",
            "Ernst-Reuter-Schule",
            "Schule Ochsenwerder",
            "Grundschule am Christenberg",
            "Hans-Elm-Schule",
            "Grundschule Furpach",
            "Arnesboken-Schule Grund- und Gemeinschaftsschule mit Förderzentrum der Gemeinde Ahrensbök",
            "Grundschule Colditz",
            "Jenaplanschule Markersbach Grund-und Mittelschule in freier Trägerschaft (Staatlich anerkannte Ersatzschule)",
            "Evangelische Grundschule Forst genehmigte Ersatzschule ",
            "Schule Am Rietberg Neuburg / Regionale Schule mit Grundschule",
            "Pestalozzi-Grundschule",
            "Phorms Campus Frankfurt City",
            "Grundschule Mastershausen ",
            "Schule Schenkelsberg",
            "Grundschule Oberbrechen",
            "Freie Waldorfschule Wetterau",
            "Brüder Grimm Schule",
            "Geschwister-Scholl-Grundschule  ",
            "Chemnitzer Schulmodell Grund- und Oberschule",
            "Grund-  und Gemeinschaftsschule mit Außenstelle Grundschule Stadum",
            "Schule am Meer Grund- und Gemeinschaftsschule der Hansestadt Lübeck",
            "Friedrich-W.-Raiffeisen-Schule ",
            "Grundschule Flottkamp ",
            "Freie Montessori-Schule",
            "Zentralschule Harrislee Grund- und Gemeinschaftsschule der Gemeinde Harrislee",
            "Karl-Gärtner-Schule",
            "Bugenhagen-Schule Alsterdorf (Stadtteilschule)",
            "Schkola Ostritz Umweltmodellschule Mittelschule (Staatlich anerkannte Ersatzschule)",
            "Grundschulzentrum Robert Reiss Bad Liebenwerda",
            "Grundschule Seifersbach",
            "Grundschule Wellesweiler",
            "Carl - Anwandter - Grundschule Calau  ",
            "Freie Grundschule Regenbogen \"Carl Friedrich Benz\"",
            "Grundschule Waldschule Fürstenhausen",
            "Anna-Schmidt-Schule",
            "Joseph-von-Eichendorff-Schule",
            "Freie Schule Känguru Integrative Grundschule Altenburg",
            "Jenaplanschule Markersbach Grund- und Oberschule in freier Trägerschaft (Staatlich anerkannte Ersatzschule)",
            "Grundschule Friedensschule",
            "Grundschule Glashütte-Süd ",
            "DPFA-Schulen gemeinnützige GmbH ",
            "Grundschule ",
            "Grundschule Daubitz",
            "Evangelische Grundschule Kavelstorf",
            "Brüder-Grimm-Schule Grundschule der Stadt Leipzig",
            "Grundschule Herolz",
            "Wilhelm-Busch-Schule",
            "Grundschule Lippersdorf",
            "Grundschule am Edelgarten",
            "Grundschule Tangstedt ",
            "Schule an der Wigmodistraße ",
            "Neddermeyer-Grundschule Schmachtenhagen ",
            "Lutherschule ",
            "Grundschule Kaltenweide ",
            "Grundschule Doberschütz",
            "Schule Arsten ",
            "Grundschule Lütte School ",
            "Grundschule Hessisches Kegelspiel",
            "Johann-Christian-Senckenberg-Schule",
            "KNEIPP-Grundschule",
            "Grundschule ",
            "Grundschule Marbach",
            "Kleebachschule",
            "DPFA-Regenbogen-Oberschule Rabenau (Staatlich anerkannte Ersatzschule))",
            "Grundschule Beucha",
            "Montessorischule Marburg",
            "Montessori-Integrationsschule (Grundschule) Nohra ",
            "Waldstadt-Grundschule  ",
            "private Vorschule Koglin",
            "Montessori-Schule Chemnitz Freie integrative Grundschule (Staatlich anerkannte Ersatzschule)",
            "Gemeinnützige Gesellschaft TÜV Rheinland Bildungswerk mbH Berufsfachschulen für Altenpflege, Wirtschaft und Technik, Fachoberschule für Gestaltung und Technik Ersatzschulen",
            "Grundschule ",
            "Löwenzahn-Grundschule Großpösna",
            "Montessori-Schule Bad Dürkheim",
            "Kindergarten ",
            "Auenland Grundschule Malborn  ",
            "Riedschule",
            "Freie Cèlestin-Freinet-Schule Grundschule (Staatlich anerkannte Ersatzschule)",
            "Brüder-Grimm-Schule ",
            "Goldwiesenschule Grundschule Echterdingen",
            "2. Grundschule Weißwasser ",
            "Theodor-Heuss-Schule  ",
            "Heinz-Sielmann-Grundschule Crinitz  ",
            "DPFA-Regenbogen-Grundschule Rabenau (Staatlich anerkannte Ersatzschule))",
            "Grundschule Hinterweidenthal  ",
            "Schule Knauerstraße",
            "Grundschule Insheim  ",
            "39. Schule Grundschule der Stadt Leipzig",
            "Freie Aktive Schule Grund- und Werkrealschule",
            "UNIVERSITAS, Grundschule mit Integrierter Gesamtschule in freier Trägerschaft",
            "Grundschule Kuntzehöhe",
            "85. Schule Grundschule der Stadt Leipzig",
            "Sorbische Grundschule ",
            "Grundschule Surendorf ",
            "Schule Alsterredder",
            "Sorbische Grundschule Bautzen",
            "Grundschule Dreiländereck  Schule der Gemeinde Perl",
            "Grund- und Oberschule Rüdersdorf ",
            "Grundschule Großrückerswalde",
            "Dittesschule Grundschule",
            "Grundschule Langsur  ",
            "Grundschule Heidhorst",
            "Schule Brückenhof-Nordshausen",
            "Grundschule Fürfeld  ",
            "Grund- und Realschule plus ",
            "Grundschule Grünhain- Beierfeld",
            "Evangelische Grundschule Lübben -anerkannte Ersatzschule- ",
            "Kinderzeit-Schule",
            "Michaelschule",
            "Konrad-Sprengel-Schule  ",
            "Evangelische Grundschule Finsterwalde anerkannte Ersatzschule",
            "Grundschule Erla-Crandorf",
            "Schule am Tornowsee - Schule mit dem sonderpäd. Förderschwerpunkt emotionale und soziale Entwicklung Pritzhagen ",
            "Albertine-Scherer-Schule ",
            "Loki-Schmidt-Schule",
            "Ameisenbergschule Grund- und Hauptschule",
            "Carl-Benz-Grundschule Bad Cannstatt",
            "Falkert-Schule Grund- und Hauptschule mit Werkrealschule",
            "Steinenbergschule Grund- und Werkrealschule Hedelfingen",
            "Grundschule Kayh",
            "Schule Schnuckendrift",
            "Grundschule Glienick  ",
            "Wasenäckerschule Grundschule Scharnhausen",
            "Grundschule \"Zum Wasserturm\"",
            "Grundschule am Weinberg  ",
            "Johannes-Kepler-Schule Grund- und Hauptschule mit Werkrealschule",
            "Grundschule \"Dr.Otto Steinfatt\"",
            "Schule Rönneburg",
            "Werner-Seelenbinder-Grundschule  ",
            "Grundschule Steindorf-Albshausen",
            "Regionale Schule mit Grundschule Gingst",
            "Theodor-Fontane-Grundschule Ludwigsfelde ",
            "Waldschule Oranienburg Grundschule ",
            "Ernst-Reuter-Schule  ",
            "Risby Danske Skole Grundschule mit Gemeinschaftsschulteil",
            "Freie Schule Rügen, Grundschule mit schulartunabhängiger Orientierungsstufe in freier Trägerschaft",
            "Grundschule Adelberg",
            "Grundschule Straßenhaus ",
            "Dominikschule ",
            "Astrid-Lindgren-Grundschule  ",
            "Ursenwangschule Grund- und Werkrealschule",
            "Paulo Freire, Ev. Grundschule mit schulartunabhängiger Orientierungsstufe in freier Trägerschaft-Staatlich genehmigte Ersatzschule mit staatlich anerkanntem Grundschulteil-",
            "Freie Schule Leipzig e. V. (Staatlich genehmigte Ersatzschule)",
            "Staufeneckschule Grund- und Werkrealschule",
            "Leipzig International School Vorschule bis Klasse 12 (Staatlich genehmigte Ersatz- und Ergänzungsschule)",
            "Hornwiesen-Grundschule",
            "Regenbogen-Grundschule Rochlitz",
            "Erich-Kästner-Schule Grundschule Diezenhalde",
            "Grund- und Werkrealschule",
            "Grundschule Hohengehren",
            "Grundschule mit Förderzentrumsteil St. Nicolai Grundschule mit Förderzentrumsteil der Gemeinde Sylt in Sylt",
            "Theodor-Mommsen-Schule Grundschule des Schulverbandes Eiderstedt",
            "Bruckenacker-Schule Grundschule Bernhausen",
            "Grundschule Crossen",
            "Private Grundschule St. Marien ",
            "Grundschule Forst Mitte  ",
            "Michael-Ende-Schule  ",
            "Grundschule \"Ploggensee\"",
            "Grundschule Höckendorf",
            "Grundschule Zossen/Dabendorf  ",
            "Bugenhagen-Schule ",
            "74. Grundschule Dresden",
            "Grundschule im Spielzeugdorf",
            "Heinrich-Mann-Schule Grund- und Gemeinschaftsschule der Hansestadt Lübeck",
            "Freie Schule Untertaunus e.V.",
            "Schule am Katzenberg",
            "Dahlmannschule",
            "Grundschule Oberhermsdorf",
            "Meisterschule",
            "Eichwaldschule",
            "Schule Eberhofweg",
            "Grundschule Zodel\"Trauott Gerber\"",
            "Adolph-Diesterweg-Schule Weidenhausen",
            "Carl-Orff-Schule ",
            "Grundschule Aufenau",
            "Grundschule ",
            "Breitwiesenschule Grundschule Hochdorf",
            "Schule Rotenhof Grundschule der Stadt Rendsburg",
            "Dittesschule Grundschule",
            "Grundschule Warderfelde ",
            "Grundschule Glienicke  ",
            "47. Grundschule Dresden",
            "Pater-Wald-Schule  ",
            "Grundschule Weidenhain",
            "Evangelische Grundschule Apolda ",
            "Astrid-Lindgren-Schule Büdelsdorf",
            "Grundschule Ulzburg ",
            "Gebrüder-Grimm-Grundschule",
            "Grundschule ",
            "Schule Klein Flottbeker Weg",
            "DUALINGO - Bilinguale Ganztagsgrundschule Jena DRK-KV Jena-Eisenberg-Stadtroda e.V.",
            "Grundschule Glösa",
            "Schule am Sonderburger Platz ",
            "Nordlicht-Schule",
            "Grundschule Wiesenfeld ",
            "Grundschule am Wald ",
            "Jüdische Grundschule Stuttgart",
            "Freie Montessori Schule Heidelberg",
            "Grundschule Raidwangen",
            "Grundschule Jeserig  ",
            "Grundschule Limbach",
            "Schule Surenland",
            "Schkola Oberland Freie Grundschule (Staatlich genehmigte Ersatzschule)",
            "Paul-Maar-Grundschule  ",
            "Aueschule Finkenwerder",
            "Grundschule Goethe-Schule ",
            "Freie Montessori Grundschule Hangelsberg anerkannte Ersatzschule",
            "Paul-Gerhardt-Schule Hanau",
            "Schule Bekassinenau",
            "Schule Vogelsang ",
            "Grundschule Datzeberg",
            "Dr.-Martin-Luther-Schule Freie Lutherische Grundschule (Staatlich anerkannte Ersatzschule)",
            "Kinderakademie Evangelische Grundschule ",
            "Friedrich-Fröbel-Schule - Grundschule der Stadt Leipzig",
            "Käthe-Kollwitz-Schule",
            "Grundschule Großlohering",
            "Goetheschule Staufenberg",
            "Wilhelm-Hauff-Schule",
            "Grundschule St. Martin ",
            "Schule Auf den Heuen ",
            "Grundschule Fichtenwalde  ",
            "Grundschule Parthenstein",
            "Schule Liebertwolkwitz Grundschule der Stadt Leipzig",
            "Alwin-Lensch-Schule ",
            "Luginslandschule Stuttgart",
            "Freie Christliche Schule ",
            "Grundschule Plauen-Oberlosa",
            "Uplandschule",
            "Grundschule Schlierbach",
            "SRH Montessori-Grundschule Dresden (Staatlich genehmigte Ersatzschule)",
            "Freie Waldorfschule Frankfurt",
            "Jahn-Grundschule",
            "Grundschule Mengsberg-Momberg",
            "Muhliusschule Grundschule der Landeshauptstadt Kiel",
            "Geschwister-Scholl-Schule",
            "Freie Schule Marburg",
            "Udo-van-Meeteren-Grundschule",
            "Adolph-Schönfelder-Schule",
            "Goetheschule",
            "Präsident Mohr Schule ",
            "Kinderschule Oberhavel Grundschule anerkannte Ersatzschule",
            "Schule Marli ",
            "Freie Waldorfschule Marburg",
            "Dresden International School (Internationale Gesamtschule, Staatlich genehmigte Ersatzschule, anerkannte Ergänzungsschule)",
            "Evangelische Werkschule Naundorf - Oberschule (Staatlich anerkannte Oberschule)",
            "Abendoberschule Chemnitz",
            "Schule im Emsbachtal",
            "Schulzentrum Marienhöhe",
            "Alteburg-Schule",
            "Pestalozzi-Mittelschule Wurzen",
            "Gesamtschule Am Rosenberg",
            "Torwiesenschule der Diakonie Stetten e.V.",
            "Erzgebirgskolleg",
            "Martinus-Schule Grund- und Realschule plus",
            "Stadtteilschule Bramfeld",
            "Metropolitan School Frankfurt",
            "Karl-Müchler-Schule  ",
            "Sabine-Ball-Schule",
            "Burgwaldschule",
            "Deutschherrenschule",
            "Konrad-Haenisch-Schule",
            "Gesamtschule Ebsdorfer Grund",
            "Achatschule St. Egidien Oberschule mit Berufsorientierung in freier Trägerschaft",
            "ecolea | Internationale Schule Güstrow",
            "Leo-Sternberg-Schule",
            "Realschule plus Bad Ems Nassau",
            "August-Hermann-Francke-Schule",
            "Bilinguale Montessori-Schule  ",
            "Mittelpunktschule Wohratal",
            "Ludwig-Börne-Schule",
            "Evangelisches Schulzentrum Muldental (Staatlich anerkannte Ersatzschule)",
            "Johannes-Gutenberg-Schule",
            "Freie Waldorfschule Wernstein",
            "Schkola Oberland¨Freie Schule an der Haine Gymnasium (Staatlich genehmigte Ersatzschule)",
            "Freie Schule der Region Zingst/Darss/Fischland Prerow, Integrierte Gesamtschule mit Grundschule und gymnasiale Oberstufe in freier Traegerschaft",
            "Wartburg International School Europe: Bilinguale Bildung in Deutschlands grüner Mitte",
            "Walter-Kolb-Schule",
            "Staatliches Abendgymnasium mit Abendschule St. Georg",
            "Mathildenschule - Verbundene Schule der Stadt Offenbach am Main",
            "Internationale Oberschule Niederwürschnitz (ION), Staatlich anerkannte Ersatzschule",
            "Internationale Oberschule Reinsdorf (IOR), Staatlich anerkannte Ersatzschule",
            "Internationale Oberschule Meerane (IOM), Staatlich anerkannte Ersatzschule",
            "TRIAS Oberschule Elsterberg (TOS), Staatlich anerkannte Ersatzschule",
            "Anne-Frank-Realschule plus Montabaur",
            "Realschule plus Daaden ",
            "Karl-Preising-Schule",
            "Heinrich-Mann-Schule",
            "Campus Klarenthal",
            "Erich Kästner-Realschule plus ",
            "Realschule plus  ",
            "Kurpfalz-Realschule plus ",
            "Erwachsenenschule (Schulzentrum für Erwachsene)",
            "Freiherr-vom-Stein-Schule - Europaschule Gladenbach",
            "Johann-Christoph-Blumhardt-Schule Freie evangelische Grund- und Werkrealschule und berufliches Gymna",
            "Langenbergschule",
            "Evangelische Montessori Oberschule Plauen (Staatlich genehmigte Ersatzschule)",
            "Stadtschule Schlüchtern",
            "Kurfürst-Balduin-Realschule  ",
            "Tümpelgarten-Schule",
            "Semper-Oberschule Dresden",
            "Freie Schule Schwepnitz (Staatlich anerkannte Oberschule)",
            "Landschulheim Grovesmühle gGmbH   ",
            "Oberschule Oederan",
            "Freie Christliche Schule Lüdenscheid -Realschule -",
            "Private Mädchenrealschule St. Josef",
            "Lietz-Internat Hohenwehrda",
            "Realschule plus Meisenheim ",
            "CJD Jugenddorf-Christophorusschule Oberurff",
            "Oberschule",
            "IGS Eschersheim",
            "Mittelschule der HOGA Schulen Dresden",
            "Mittelpunktschule Adorf",
            "Obermayr Europa-Schule",
            "Realschule plus am Speyerbach",
            "Goldbachschule Frohnhausen",
            "Oberschule und Fachoberschule Sabel Freital (staatlich anerkannt)",
            "Abendschule Vor dem Holstentor",
            "Friedrich-Fröbel-Schule",
            "Marianum Fulda",
            "Mittelpunktschule Dautphetal",
            "Ernst-Reuter-Schule",
            "Hans-Elm-Schule",
            "Bachschule",
            "Werratalschule",
            "Stadtteilschule Arheilgen",
            "Private Edith-Stein-Realschule ",
            "Elisabethenschule",
            "Gemeinnützige Gesellschaft TÜV Rheinland Bildungswerk mbH Berufsfachschulen für Altenpflege, Wirtschaft und Technik, Fachoberschule für Gestaltung und Technik Ersatzschulen",
            "Anne-Frank-Realschule plus ",
            "Alfred-Delp-Schule",
            "Realschule plus Pirmasens",
            "Realschule plus Eisenberg ",
            "Grund- und Realschule plus ",
            "Nelson Mandela RS+  ",
            "Realschule plus  ",
            "Augustiner  ",
            "Bischöfliche Realschule ",
            "Realschule plus  ",
            "Eichwaldschule",
            "Friedrich-Ebert-Schule",
            "Gemeinschaftsschule/ERS Anton Hansen-Schule",
            "Abendhaupt- u. Abendrealschule Frankfurt",
            "Erweiterte Realschule / Gemeinschaftsschule Eppelborn",
            "Werner-von-Siemens-Schule",
            "Kaulbach-Schule",
            "Brüder-Grimm-Schule",
            "Kooperative Gesamtschule ",
            "Realschule Kirn  ",
            "Gymnasium und Realschule für Erwachsene",
            "Priv. Realschule der Ursulinen ",
            "Alfred-Delp-Schule  ",
            "Realschule Zell  ",
            "Simon-Salomon-Realschule ",
            "St. Franziskus-Realschule ",
            "St.-Katharina-Realschule ",
            "Private Maria-Ward Realschule ",
            "Bischöfliche Willigis ",
            "Fritz-Straßmann-Realschule ",
            "Priv. Schönstätter  ",
            "Bischöfliche Realschule ",
            "Realschule Lahnstein  ",
            "Blandine-Merten-Realschule ",
            "Ahrtalschule ",
            "Freiherr von Boeselager ",
            "Brohltalschule ",
            "Realschule plus  ",
            "Realschule plus Sinzig ",
            "Realschule plus  ",
            "Bertha-von-Suttner Realschule ",
            "Westerwaldschule  ",
            "Realschule plus Herdorf ",
            "Marion-Dönhoff ",
            "Gustav-Heinemann-  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus Wöllstein ",
            "Realschule plus Wörrstadt ",
            "Erich-Kästner-Realschule plus ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus Kirn  ",
            "Realschule plus  ",
            "Freiherr-vom-Stein  ",
            "Realschule plus Manderscheid  ",
            "Realschule plus Salmtal ",
            "Erbeskopf-Realschule plus ",
            "Clara-Viebig-Realschule plus W ",
            "Realschule plus Baumholder ",
            "Realschule plus  ",
            "Kooperative Realschule plus  ",
            "Realschule plus Cochem ",
            "Realschule plus Vulkaneifel  ",
            "Nordpfalzschule  ",
            "Georg-von-Neumayer-Schule ",
            "Realschule plus Rockenhausen  ",
            "Albert-Schweitzer-Schule ",
            "Realschule plus  ",
            "Priv. Realschule plus St. Matthias ",
            "Realschule plus  ",
            "Friedrich-Schiller-  ",
            "Friedrich-Ebert-  ",
            "Realschule plus Bellheim ",
            "Richard-von-Weizsäcker- ",
            "Geschwister-Scholl-Schule ",
            "Realschule plus Rülzheim ",
            "Dorschbergschule  ",
            "Lina-Pfaff  ",
            "Adam-Müller-Schule  ",
            "Realschule plus Queidersbach  ",
            "Westpfalzschule Weilerbach ",
            "Clemens-Brentano-/ Overberg  ",
            "Realschule plus  ",
            "Albert Schweitzer Schule ",
            "Realschule plus  ",
            "Gustav-Schäffner-Schule ",
            "Realschule plus Kusel ",
            "Realschule plus  ",
            "Realschule plus Landau ",
            "Anne-Frank-Realschule plus ",
            "Adolf-Diesterweg-Realschule + ",
            "Realschule plus am Ebertpark  ",
            "Kanonikus-Kir-Realschule plus ",
            "Realschule plus  ",
            "Christian-Erbach-Realschule pl ",
            "Kaiserpfalz ",
            "Wilhelm-Holzamer-Schule ",
            "Realschule plus Nackenheim ",
            "Realschule plus Sprendlingen  ",
            "Geschwister-Scholl  ",
            "Karl-Fries-Realschule plus ",
            "Albert-Schweitzer  ",
            "Realschule plus  ",
            "Realschule plus Nachtsheim ",
            "Realschule plus Pellenz ",
            "Realschule plus Vallendar ",
            "Realschule plus Neustadt ",
            "Nelson Mandela ",
            "Realschule plus Linz  ",
            "Realschule plus  ",
            "Heinrich-Heine ",
            "Realschule plus Niederbieber  ",
            "Realschule plus Puderbach ",
            "Realschule plus Rheinbrohl ",
            "Stefan-Andres-Schule  ",
            "Realschule plus  ",
            "Landgraf-Ludwig  ",
            "Realschule plus Boppard ",
            "Ausonius-Realschule plus ",
            "Heuss-Adenauer ",
            "Puricelli-Schule  ",
            "Realschule plus Simmern ",
            "Theodissa Realschule plus Diez ",
            "Realschule plus Hahnstätten  ",
            "Realschule plus Nastätten ",
            "Peter-Gärtner ",
            "Rudolf-Wihr-Realschule plus  ",
            "Justus-von-Liebig-Realschule  ",
            "Burgfeld-Schule  ",
            "Realschule Plus Siedlungsschul ",
            "Nikolaus-von-Weis-Realschule p ",
            "Realschule plus Maikammer-Hamb ",
            "Realschule plus Contwig ",
            "Wasgauschule Hauenstein - Real ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Kurfürst-Balduin  ",
            "Privatschule St. Maximin ",
            "Realschule Plus  ",
            "Realschule plus  ",
            "Realschule plus Bad Marienberg ",
            "Realschule plus  ",
            "Heinrich-Roth-Schule  ",
            "Freiherr-vom-Stein-Realschule ",
            "Erich Kästner Realschule plus ",
            "Realschule plus  ",
            "Realschule plus Salz  ",
            "Realschule plus  ",
            "Theodor-Heuss-Realschule plus ",
            "Karmeliter Realschule plus ",
            "Westend-Realschule plus ",
            "Nibelungen-Realschule plus ",
            "Pfrimmtal  ",
            "Mannlich-Realschule plus ",
            "Realschule plus mit  ",
            "Realschule plus  ",
            "Realschule plus Kaisersesch  ",
            "Gutenbergschule  ",
            "Realschule plus  ",
            "Konrad-Adenauer  ",
            "Rochus-Realschule plus ",
            "Carl-Zuckmayer-Realschule plus ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Realschule plus mit  ",
            "Realschule plus  ",
            "Realschule plus  ",
            "Kreisrealschule Gelnhausen",
            "Werner-von-Siemens-Schule",
            "Realschule plus  ",
            "Stiftung Deutsche Landeserziehungsheime Hermann-Lietz-Schule Haubinda Staatlich anerkannte Regelschule",
            "Erweiterte Realschule",
            "Realschule Maria Stern Augsburg des Schulwerks derDiözese Augsburg",
            "Staatliche Realschule Neustadt b.Coburg ",
            "Georg-Hipp-Realschule Staatliche Realschule Pfaffenhofen a.d.Ilm",
            "Knabenrealschule Rebdorf der Diözese Eichstätt ",
            "Realschule am Judenstein  Staatliche RealschuleRegensburg I",
            "Adolf-Reichwein-Schule",
            "St.-Angela-Schule",
            "Kreisrealschule Bad Orb",
            "Europa-Schule Dr. Obermayr e.V.",
            "Haupt- und Realschule Birstein",
            "Sophie-Scholl-Schule",
            "Realschule plus  ",
            "Gesamtschule Schenklengsfeld",
            "Realschule plus und Fachoberschule Gesundheit Traben-Trarbach",
            "Heinrich-von-Bibra-Schule",
            "Theodor-Litt-Schule",
            "Realschule plus Lingenfeld ",
            "Freie Schule Rerik, Integrierte Gesamtschule mit gymnasialer Oberstufe",
            "Realschule plus  ",
            "Obermayr  International School",
            "Freiherr-von-Schütz-Schule",
            "Johann-Textor-Schule",
            "Realschule plus Saarburg ",
            "Realschule plus Eich  ",
            "Realschule plus Bobenheim- ",
            "Friedrich-Stoltze-Schule",
            "K.-Burger-Realschule plus ",
            "Hermann-Neuberger-Schule Erweiterte Realschule Völklingen",
            "Realschule plus Neuwied ",
            "Graf Anton Schule Wadern -Erweiterte Realschule / Gemeinschaftsschule-",
            "Eduard-Spranger-Schule",
            "Hildegardisschule",
            "Wilhelm-Leuschner-Schule",
            "Pestalozzischule Gießen",
            "Ernst-Reuter-Schule",
            "Erich-Kästner-Schule",
            "Heinrich-von-Kleist-Schule",
            "Ludwig-Erhard-Schule",
            "Freiherr-vom-Stein-Schule",
            "Dietrich-Bonhoeffer-Schule",
            "Eugen-Bachmann-Schule",
            "Schillerschule",
            "Stadtschule Biedenkopf",
            "Mittelpunktschule Hartenrod",
            "Mittelpunktschule Oberes Perftal",
            "Schule am Dohlberg",
            "Haupt- und Realschule Nidda",
            "Otzbergschule",
            "Fritz-Philippi-Schule Breitscheid",
            "Johann-Heinrich-Alsted-Schule",
            "Stadtschule am Solgraben",
            "John-F.-Kennedy-Schule",
            "Stadtschule Butzbach",
            "Karl-Weigand-Schule",
            "Mittelpunktschule Oberer Hüttenberg",
            "Geschwister-Scholl-Schule Niddatal",
            "Erich-Kästner-Schule Rosbach",
            "Anton-Calaminus-Schule",
            "Friedrich-Ebert-Schule",
            "Gerhart-Hauptmann-Schule",
            "Parkschule",
            "Mittelpunktschule Trebur",
            "Mittelpunktschule St. Blasius",
            "Erlenbachschule",
            "Johann-Wolfgang-von-Goethe-Schule",
            "Theodor-Heuss-Schule",
            "Mittelpunktschule Goldener Grund",
            "Adolf-Reichwein-Schule",
            "Kreuzburgschule",
            "Brüder-Grimm-Schule",
            "Eppsteinschule",
            "Brüder-Grimm-Schule",
            "Max-Ernst-Schule",
            "Kellerskopfschule",
            "Heinrich-von-Gagern-Schule",
            "Schule an der Wascherde",
            "Westerwaldschule",
            "Geschwister-Scholl-Schule",
            "Freie Christliche Schule",
            "Neue Friedensschule/Sinn",
            "Erich Kästner-Schule Oberursel",
            "Konrad-Lorenz-Schule",
            "Michael-Ende-Schule",
            "Marianne-Frostig-Schule",
            "Alexander-von-Humboldt-Schule",
            "Merianschule",
            "Schulzentrum Hessen-Homburg",
            "Rackow-Schule Frankfurt",
            "Paul-Gerhard-Schule Hanau, Realschule",
            "Geschwister-Scholl-Schule",
            "Anne-Frank-Schule",
            "Falkschule",
            "Fürstenbergerschule",
            "Robert-Koch-Schule",
            "Gutenbergschule",
            "Gerhart-Hauptmann-Schule",
            "Werner-von-Siemens-Schule",
            "Albrecht-Dürer-Schule",
            "Johann-von-Nassau-Schule",
            "Comenius-Schule",
            "Maria-Ward-Schule",
            "Private Realschule Herrmann",
            "Theodor-Fliedner-Schule",
            "Bardoschule",
            "Fasanenhofschule",
            "Friedrich-Wöhler-Schule",
            "Valentin-Traudt-Schule",
            "Emil-von-Behring-Schule",
            "Theodor-Heuss-Schule - Europaschule",
            "Südringgauschule",
            "Friedrich-Ebert-Schule",
            "Ortenbergschule",
            "Cornelia-Funke-Schule",
            "Ederseeschule Herzhausen",
            "Anne-Frank-Schule",
            "Erich Kästner-Schule",
            "Ohetalschule Verna",
            "Lüdertalschule",
            "Mittelpunktschule Hohe Rhön",
            "Biebertalschule",
            "Ense-Schule",
            "Schlossbergschule Rhoden",
            "Mittelpunktschule Goddelsheim",
            "Mittelpunktschule Sachsenhausen",
            "Kugelsburgschule",
            "Schule im Ostergrund",
            "Jahnschule Hünfeld",
            "Von-Galen-Schule Eichenzell",
            "Freie Christliche Schule Kassel",
            "Montessori Schule",
            "Luisenschule",
            "Friedrich-Ebert-Schule",
            "Konrad-Adenauer-Schule",
            "Louis-Peter-Schule",
            "Willi-Graf-Realschule",
            "Maximilian-Kolbe-Schule",
            "Albertus-Magnus-Realschule (privat)",
            "Erweiterte Realschule Bruchwiese",
            "Erweiterte Realschule",
            "Private Erweiterte Realschule des Don-Bosco-Schulvereins",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule Quierschied",
            "Erweiterte Realschule Am Vopeliuspark Sulzbach",
            "Erweiterte Realschule Am Sonnenhügel",
            "Friedrich-Bernhard-Karcher-Schule Beckingen -Erweiterte Realschule-",
            "Erweiterte Realschule",
            "Eichenlaubschule Weiskirchen -Erweiterte Realschule-",
            "Erweiterte Realschule",
            "Erweiterte Realschule Neunkirchen Stadtmitte und Wiebelskirchen",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Theeltalschule -Erweiterte Realschule-",
            "Nikolaus-Gross-Schule (Erweiterte Realschule)",
            "Erweiterte Realschule",
            "Erweiterte Realschule I",
            "Erweiterte Realschule II",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule I",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule",
            "Erweiterte Realschule in Abendform",
            "Realschule plus Bad Kreuznach ",
            "Realschule plus  ",
            "Realschule plus Bleialf ",
            "Ernst-Reuter-Schule  ",
            "Realschule plus  ",
            "St. Thomas Realschule plus ",
            "Realschule plus  ",
            "Realschule plus Daun  ",
            "Herzog-Wolfgang  ",
            "Mädchenrealschule Marienburg, Abenberg. der Diözese Eichstätt ",
            "Johann-Turmair-Realschule Staatliche Realschule Abensberg ",
            "Wittelsbacher-Realschule Staatliche Realschule Aichach ",
            "Angela-Fraundorfer-Realschule für Mädchen der Franziskanerinnen Aiterhofen",
            "Herzog-Ludwig-Realschule Staatliche Realschule Altötting ",
            "Maria-Ward-Realschule Altötting der Maria-Ward-SchulstiftungPassau",
            "Edith-Stein-Schule Staatliche Realschule Alzenau ",
            "Dr.-Johanna-Decker-Realschule Amberg der Schulstiftung der Diözese Regensburg",
            "Theresia-Gerhardinger-Realschule der Diözese Würzburg Amorbach ",
            "Staatliche Realschule für Knaben Aschaffenburg ",
            "Ruth-Weiss-Realschule Staatliche Realschule für Mädchen Aschaffenburg",
            "Maria-Ward-Schule Aschaffenburg Mädchenrealschule der Maria-Ward-Stiftung Aschaffenburg",
            "Walter-Mohr-Realschule Staatl. Realschule Traunreut ",
            "Realschule des Zweckverbandes Auerbach ",
            "Bertolt-Brecht-Realschule Staatl. Realschule Augsburg I ",
            "Heinrich-von-Buz-Realschule Staatliche Realschule Augsburg II ",
            "Städtische Agnes-Bernauer-Schule Augsburg Realschule für Mädchen ",
            "Mädchenrealschule St.Ursula Augsburg des Schulwerks der Diözese Augsburg",
            "Maria-Ward-Realschule Augsburg d. Schulwerks d. Diözese Augsburg ",
            "A.B. von Stettensches Institut Augsburg Realschule für Mädchen ",
            "Wilhelm-Leibl-Schule Staatliche Realschule Bad Aibling ",
            "Staatliche Realschule Bad Kissingen ",
            "Staatl. Realschule Obertraubling  ",
            "Werner-von-Siemens-Realschule Staatl. Realschule Bad Neustadt a.d.Saale",
            "Maria-Ward-Schule Mädchenrealschule St. Zeno Bad Reichenhall",
            "Städtische Graf-Stauffenberg- Realschule Bamberg ",
            "Maria-Ward-Realschule Bamberg  ",
            "Alexander-von-Humboldt-Realschule Staatliche Realschule Bayreuth I ",
            "Johannes-Kepler-Realschule Staatliche Realschule Bayreuth II ",
            "Altmühltal-Realschule Staatliche Realschule Beilngries ",
            "Staatliche Realschule Bobingen  ",
            "Ludmilla-Schule Staatliche Realschule Bogen ",
            "Private Realschule mit Schüler(innen)heim Schloß Brannenburg",
            "Staatliche Realschule Bad Brückenau ",
            "Staatliche Realschule Buchloe  ",
            "Markgrafen-Realschule Staatliche Realschule Burgau ",
            "Maria-Ward-Realschule Burghausen der Maria-Ward-SchulstiftungPassau",
            "Staatliche Realschule Burgkunstadt ",
            "Realschule am Kreuzberg Staatliche Realschule Burglengenfeld",
            "Maristen-Realschule Cham der Schulstiftung der Diözese Regensburg",
            "Gerhardinger-Realschule Cham der Schulstiftung der Diözese Regensburg",
            "Staatliche Realschule Coburg I  ",
            "Staatliche Realschule Coburg II  ",
            "Realschule Deggendorf  der Maria-Ward-SchulstiftungPassau",
            "Liebfrauenschule Dießen Mädchenrealschule des Schulwerks der Diözese Augsburg",
            "St. Bonaventura-Realschule Dillingen des Schulwerks der Diözese Augsburg",
            "Herzog-Tassilo-Realschule Staatliche Realschule Dingolfing ",
            "Knabenrealschule Hl. Kreuz Donauwörth des Schulwerks der Diözese Augsburg",
            "Mädchenrealschule St. Ursula Donauwörth des Schulwerks der Diözese Augsburg",
            "Staatliche Realschule Ebermannstadt ",
            "Dr.-Ernst-Schmidt-Realschule Staatliche Realschule Ebern ",
            "Dr.-Wintrich-Schule Staatliche Realschule Ebersberg ",
            "Steigerwaldschule Staatliche Realschule Ebrach ",
            "Stefan-Krumenauer-Schule Staatliche Realschule Eggenfelden ",
            "Maria-Ward-Realschule der Diözese Eichstätt ",
            "Herzog-Tassilo-Realschule Staatliche Realschule Erding ",
            "Mädchenrealschule Heilig Blut Erding der Erzdiözese München und Freising",
            "Werner-von-Siemens-Realschule Staatliche Realschule Erlangen I ",
            "Staatliche Realschule Feucht  ",
            "Johann-Georg-von-Soldner-Schule Staatl. Realschule Feuchtwangen ",
            "Georg-Hartmann-Realschule Staatliche Realschule Forchheim ",
            "Staatliche Realschule für Knaben Freilassing ",
            "Mädchenrealschule Franz von Assisi der Erzdiözese München und Freisingin Freilassing-Salzburghofen",
            "Karl-Meichelbeck-Realschule Staatl. Realschule Freising ",
            "Staatliche Realschule Freyung  ",
            "Konradin-Realschule - Staatl. Realschule Friedberg - ",
            "Ferdinand-von-Miller-Realschule Staatliche Realschule Fürstenfeldbruck",
            "Leopold-Ullstein-Realschule - Staatliche Realschule Fürth - ",
            "Hans-Böckler-Schule Städt. Realschule Fürth ",
            "Johann-Jakob-Herkomer-Schule Staatliche Realschule Füssen ",
            "Staatliche Realschule Furth i.Wald ",
            "Freie Waldorfschule Marburg",
            "Futurum Vogtland Evangelisches Gymnasium Mylau (Staatlich anerkannte Ersatzschule)",
            "Elsterschloss-Gymnasium  ",
            "Stiftung Louisenlund",
            "ecolea | Internationale Schule Schwerin",
            "Dresden International School (Internationale Gesamtschule, Staatlich genehmigte Ersatzschule, anerkannte Ergänzungsschule)",
            "Gymnasium, Kolleg und Fachoberschule St. Matthias Wolfratshausen",
            "Schulzentrum Marienhöhe",
            "Albertus-Magnus-Schule",
            "ecolea | Internationale Schule Rostock",
            "Gymnasium Panketal Freie Stadtrandschule im Grünen anerkannte Ersatzschule",
            "Max-Planck-Gymnasium",
            "Christoph-Graupner-Gymnasium Kirchberg",
            "Auguste-Viktoria-Schule",
            "Bilinguale Grundschule PHORMS Hamburg",
            "Gesamtschule Am Rosenberg",
            "Erzgebirgskolleg",
            "Voltaireschule -  Gesamtschulcampus mit gymnasialem Bildungsgang",
            "Berufliches Schulzentrum für Wirtschaft und Gesundheit ",
            "Stadtteilschule Bramfeld",
            "Metropolitan School Frankfurt",
            "Privates Ganztagsgymnasium IBB gGmbH (Staatlich genehmigte Ersatzschule)",
            "Karl-Müchler-Schule  ",
            "Sabine-Ball-Schule",
            "Gymnasium Friedrich Anton von Heinitz ",
            "Justus-Liebig-Schule",
            "Leibniz Privatschule Elmshorn Kindergarten, Grund-, Gemeinschaftsschule, Gymnasium und IB Diploma - internationales ABITUR",
            "Albert-Schweitzer-Schule Alsfeld",
            "Vicco-von-Bülow-Gymnasium",
            "Stiftung St. Matthias Waldram, mit Gymnasium Kolleg und Fachoberschule",
            "Private Marienschule",
            "thuringia international school - weimar  ",
            "Oberstufenzentrum Lausitz  ",
            "Alstergymnasium Henstedt-Ulzburg",
            "Gesamtschule Ebsdorfer Grund",
            "Gymnasium im Stift Neuzelle Staatlich anerkannte Ersatzschule Schule mit internationaler Ausricht",
            "Bilinguales Gymnasium Phorms Hamburg",
            "Christliche Schule Johanneum (Staatlich anerkanntes Gymnasium/genehmigte Oberschule )",
            "ecolea | Internationale Schule Güstrow",
            "Freies Christliches Gymnasium Düsseldorf (Staatl. anerkannte Ersatzschule)",
            "Evangelisches Gymnasium Hermannswerder - mit Internat - ",
            "Ricarda-Huch-Schule",
            "FORTIS-AKADEMIE gGmbH ",
            "Neues Gymnasium",
            "Hohe Schule der Wirtschaft und Dienstleistungen, just4web.cz (Sample schriftlich)",
            "Wilhelm-Gymnasium",
            "Staatliches Gymnasium \"Marie Curie\" Worbis",
            "Goethe-Gymnasium  ",
            "August-Hermann-Francke-Schule",
            "Salzmannschule Schnepfenthal Staatliches Spezialgymnasium für Sprachen",
            "Julius-Motteler-Gymnasium",
            "Luise-Büchner-Schule",
            "barnim-gymnasium bernau ",
            "Erasmus Frankfurter Stadtschule ",
            "Göttenbach-Gymnasium  ",
            "G.-E.-Lessing-Gymnasium",
            "Schulcampus Rostock-Evershagen",
            "Lycée Français de Hambourg Antoine de Saint-Exupéry",
            "Alsterring Gymnasium",
            "Gauß-Gymnasium ",
            "Christianeum",
            "Evangelisches Schulzentrum Muldental (Staatlich anerkannte Ersatzschule)",
            "Freie Waldorfschule Wernstein",
            "Frauenlob-Gymnasium  ",
            "Schkola Oberland¨Freie Schule an der Haine Gymnasium (Staatlich genehmigte Ersatzschule)",
            "Freie Schule der Region Zingst/Darss/Fischland Prerow, Integrierte Gesamtschule mit Grundschule und gymnasiale Oberstufe in freier Traegerschaft",
            "Privates Litauisches Gymnasium",
            "Wartburg International School Europe: Bilinguale Bildung in Deutschlands grüner Mitte",
            "Private Tagesheim- und Internatsschule",
            "Staatliches Abendgymnasium mit Abendschule St. Georg",
            "Georg-Büchner-Schule",
            "Sebastian-Münster-Gymnasium  ",
            "Gymnasium Hochrad",
            "Städtisches Gymnasium Carl Friedrich Gauß Mathematisch-naturwissenschaftlich-technische Spezialschule",
            "Evangelische Zinzendorfschulen Herrnhut",
            "Lahntalschule Biedenkopf",
            "Europäisches Gymnasium Meerane \"Johann Heinrich Pestalozzi\" (Staatlich anerkannte Ersatzschule )",
            "OKO Private School Talent-Schule Hamburg",
            "Europäisches Gymnasium Waldenburg (Staatlich anerkannte Ersatzschule)",
            "Freie Waldorfschule Wiesbaden",
            "Albert-Schweitzer-Schule",
            "Kleemannschule gGmbH - Private Wirtschaftsschule",
            "Evangelisches Gymnasium Doberlug-Kirchhain anerkannte Ersatzschule ",
            "Schloß Torgelow Privates Internatsgymnasium, Gymnasium in freier Trägerschaft",
            "Gymnasium auf dem Asterstein  ",
            "Internationales Gymnasium Geithain (IGG), Staatlich anerkannte Ersatzschule",
            "accadis International School",
            "Internationales Wirtschaftsgymnasium Geithain (IWG), Staatlich anerkannte Ersatzschule",
            "Abendgymnasium im RBZ Wirtschaft . Kiel",
            "Gymnasium Grootmoor",
            "Nebelthau-Gymnasium ",
            "Evangelische Schulgemeinschaft Erzgebirge (Staatlich anerkanntes Ersatzschule)",
            "Leibnizschule",
            "Heinrich-Mann-Schule",
            "Campus Klarenthal",
            "Gymnasium Harksheide ",
            "Evangelisches Gymnasium Leukersdorf (Staatlich genehmigte Ersatzschule)",
            "Gymnasium Othmarschen",
            "Gymnasium Hummelsbüttel",
            "Freiherr-vom-Stein-Schule - Europaschule Gladenbach",
            "Graf-Stauffenberg-Gymnasium",
            "Max-Planck-Gymnasium",
            "Gymnasium Nieder-Olm  ",
            "Peter-Altmeier-Gymnasium, Landesmusikgymnasium RLP",
            "Heinrich-Böll-Gymnasium ",
            "Johann-Christoph-Blumhardt-Schule Freie evangelische Grund- und Werkrealschule und berufliches Gymna",
            "Friedrich-Wilhelm-Gymnasium  ",
            "Bertolt-Brecht-Gymnasium Dresden",
            "Musikgymnasium Käthe Kollwitz",
            "Clara-Wieck-Gymnasium",
            "Staatliches Heinrich-Heine-Gymnasium ",
            "Evangelische Schule Schönefeld - Gymnasium",
            "Gutenbergschule Wiesbaden",
            "Landschulheim Grovesmühle gGmbH   ",
            "Internationales Gymnasium Reinsdorf (IGR), Staatlich anerkannte Ersatzschule",
            "Schwalmgymnasium",
            "Überwald-Gymnasium",
            "Lietz-Internat Hohenwehrda",
            "Gymnasium Altona",
            "Gymnasium der bundtStift_Schulen - Gymnasium anerkannte Ersatzschule in der Sekundarstufe I und  II (GOST)",
            "König-Heinrich-Schule",
            "Europäische Gesamtschule Insel Usedom",
            "Hansa-Gymnasium Hansestadt Stralsund",
            "Matthias-Claudius-Gymnasium",
            "Gymnasium zu St. Katharinen  ",
            "Albert-Einstein-Gymnasium",
            "CJD Jugenddorf-Christophorusschule Oberurff",
            "Städtisches Gymnasium Mittweida",
            "IGS Eschersheim",
            "Gymnasium der HOGA Schulen Dresden",
            "Wigbertschule",
            "Gymnasium Edenkoben  ",
            "Obermayr Europa-Schule",
            "Erwin-Strittmatter-Gymnasium  ",
            "Alexander-von-Humboldt-Gymnasium",
            "Gymnasium F. F. Runge Oranienburg ",
            "Merz Schule gGmbH Private Grundschule und Gymnasium",
            "Konrad Wachsmann Oberstufenzentrum  ",
            "Staatliches Gymnasium Oberhof Spezialschule für Sport",
            "Käthe-Kollwitz-Schule ",
            "Staatliches Gymnasium ",
            "Johannes-Brahms-Schule ",
            "Martin-Luther-Schule",
            "Lichtenbergschule",
            "Evangelisches Trifels-Gymnasium ",
            "Freies Gymnasium Regenbogen Zwenkau (Staatlich anerkannte Ersatzschule)",
            "Abendschule Bremerhaven ",
            "Landau-Gymnasium Weißwasser (Kreisliches Gymnasium)",
            "Marianum Fulda",
            "Einhardschule",
            "Privatschule Mittelholstein Grundschule & Gymnasium",
            "Trave-Gymnasium ",
            "Fritz-Greve-Gymnasium",
            "Kaiser-Karl-Schule ",
            "Freie Montessorischule Huckepack Berufliches Gymnasium Wirtschaftswissenschaften",
            "Carl-von-Ossietzky-Gymnasium",
            "Gymnasium Markneukirchen",
            "Phorms Campus Frankfurt City",
            "Freie Waldorfschule Wetterau",
            "Gymnasium ",
            "Goethe-Schiller-Gymnasium  ",
            "Hennebergisches Gymnasium ",
            "Werratalschule",
            "Stadtteilschule Arheilgen",
            "Anna-Schmidt-Schule",
            "Freiherr-vom-Stein-Schule ",
            "Gymnasium Wentorf ",
            "Staatliches Berufsschulzentrum Nordhausen",
            "Elisabethenschule",
            "Staatliches Gymnasium ",
            "Werner-Heisenberg-Gymnasium  ",
            "Schiller-Gymnasium  ",
            "Berufliches Gymnasium der HOGA Schulen Dresden",
            "Freies Gymnasium Borsdorf (Staatlich anerkannte Ersatzschule)",
            "Albert-Schweitzer-Gymnasium",
            "Magnus-Gottfried-Lichtwer-Gymnasium Wurzen",
            "Leibniz-Gymnasium  ",
            "Friedrich-Schiller-Gymnasium Pirna",
            "Wilhelmsgymnasium",
            "Friedrich-Ludwig-Jahn-Gymnasium  ",
            "Alte Landesschule",
            "Heilwig-Gymnasium",
            "Regionales BerufsBildungsZentrum Dithmarschen, rechtsfähige Anstalt des öffentlichen Rechts (BBZ)",
            "Karl-Friedrich-Schinkel-Gymnasium Neuruppin ",
            "Goethe-Gymnasium",
            "UNIVERSITAS, Grundschule mit Integrierter Gesamtschule in freier Trägerschaft",
            "Paul-von-Denis-Gymnasium ",
            "Internatsschule Institut Lucius",
            "Liebigschule",
            "Starkenburg-Gymnasium",
            "Chr. Gymnasium Rudolf Stempel",
            "Lise-Meitner-Gymnasium G8GTS ",
            "Paul-Fahlisch-Gymnasium Lübbenau  ",
            "Leibnizschule Gymnasium der Stadt Leipzig",
            "Reuterstädter Gesamtschule - Europaschule-",
            "Hochwaldgymnasium",
            "Gymnasium Mainz-Oberstadt ",
            "Ostsee-Gymnasium ",
            "Musikalisch-Sportliches Gymnasium (Staatlich genehmigte Ersatzschule)",
            "Städtisches Gymnasium I Frankfurt (Oder) Europaschule Karl-Liebknecht",
            "Gymnasium",
            "Priv. Martin-Butzer-Gymnasium ",
            "Staatliches Gymnasium ",
            "Goethe-Gymnasium Gera/ Rutheneum seit 1608 Staatliches Gymnasium",
            "Fördegymnasium Allgemeinbildendes Gymnasium mit Abendgymnasium",
            "Pückler-Gymnasium Cottbus  ",
            "Klosterschule Roßleben Gymnasium in freier Trägerschaft",
            "Freies Gymnasium Penig (Staatlich anerkannte Ersatzschule)",
            "Eduard-Spranger-Gymnasium ",
            "Staatliches Angergymnasium Jena",
            "SeeCampus Niederlausitz /Emil-Fischer-Gymnasium ",
            "Greifen-Gymnasium",
            "Eric-Kandel-Gymnasium  ",
            "Herzog-Ernst-Schule Staatliche Kooperative Gesamtschule des Landkreises Gotha",
            "Uplandschule",
            "Max-Steenbeck-Gymnasium  ",
            "Freie Waldorfschule Frankfurt",
            "Gustav-Hertz-Schule Gymnasium der Stadt Leipzig",
            "Innerstädtisches Gymnasium",
            "Altes Kurfürstliches Gymnasium",
            "Philipp-Melanchthon-Gymnasium Humanistisches Privatgymnasium anerkannte Ersatzschule",
            "Werner-Heisenberg-Schule Gymnasium der Stadt Leipzig",
            "Gymnasium ",
            "Marie-Curie-Gymnasium Dresden",
            "Gymnasium Brandis",
            "Freies Gymnasium Regenbogen Augustusburg",
            "Engelsburg-Gymnasium Kassel",
            "Coppernicus-Gymnasium Europaschule",
            "Humboldt-Schule",
            "Grund- und Stadtteilschule Maretstraße",
            "Ulf-Merbold-Gymnasium Staatliches Gymnasium Greiz",
            "Lößnitzgymnasium Radebeul",
            "Kooperative Gesamtschule ",
            "CJD Jugendorf-Christophorus-Schule Rostock, Gymnasium mit Grundschule und schulartunabhängiger Orientierungsstufe in freier Trägerschaft",
            "Leininger-Gymnasium  ",
            "Ostseegymnasium Greifswald,Gymnasium und Grundschule mit schulartunabhängiger Orientierungsstufe in freier Trägerschaft",
            "Freie Schule Zinnowitz, Integrierte Gesamtschule in freier Trägerschaft",
            "Greenhouse School Graal-Müritz, Integrierte Gesamtschule in freier Trägerschaft",
            "Neumühler SchuleGymnasium und Regionale Schule mitGrundschule in freier Trägerschaft",
            "Gymnasium \"Alexander von Humboldt\" Greifswald",
            "Gymnasium \"Friedrich Ludwig Jahn\" Greifswald",
            "Gymnasium Grimmen",
            "Gymnasium \"Richard Wossidlo\" Ribnitz-Damgarten",
            "\"Lilienthal-Gymnasium\" Anklam",
            "Runge-Gymnasium Wolgast",
            "Gymnasium \"Ernst Moritz Arndt\" Bergen",
            "Goethe-Gymnasium, Musikgymnasium",
            "Gymnasium Carolinum",
            "Joliot-Curie-Gymnasium",
            "Richard-Wossidlo-Gymnasium",
            "Sportgymnasium",
            "Deutsch-Polnisches Gymnasium",
            "Gymnasium \"Oskar Picht\"",
            "Gymnasium Sanitz",
            "Friderico-Francisceum-Gymnasium",
            "Geschwister-Scholl-Gymnasium",
            "Gymnasium \"John Brinckman\"",
            "Gymnasium Teterow",
            "Erasmus-Gymnasium",
            "Gymnasium Reutershagen",
            "Große Stadtschule Geschwister-Scholl-Gymnasium",
            "Gerhart-Hauptmann-Gymnasium",
            "Gymnasium \"Elbegymnasium\"",
            "Robert-Stock-Gymnasium",
            "Goethe-Gymnasium",
            "Gymnasium am Tannenberg",
            "Gymnasium Am Sonnenkamp",
            "Ernst-Barlach-Gymnasium",
            "Gymnasium Am Sonnenberg",
            "Gymnasium \"Eldenburg\"",
            "Friedrich-Franz-Gymnasium",
            "Gymnasium Fridericianum",
            "Goethe-Gymnasium",
            "Sportgymnasium",
            "Albrecht-Thaer-Gymnasium",
            "Charlotte-Paulsen-Gymnasium",
            "Emilie-Wüstenfeld-Gymnasium",
            "Friedrich-Ebert-Gymnasium",
            "Gelehrtenschule des Johanneums",
            "Goethe-Gymnasium",
            "Gymnasium Allee",
            "Gymnasium Allermöhe",
            "Gymnasium Alstertal",
            "Gymnasium Blankenese",
            "Gymnasium Bondenwald",
            "Gymnasium Bornbrook",
            "Gymnasium Buckhorn",
            "Gymnasium Corveystraße",
            "Gymnasium Dörpsweg",
            "Gymnasium Eppendorf",
            "Gymnasium Farmsen",
            "Gymnasium Finkenwerder",
            "Gymnasium Hamm",
            "Gymnasium Heidberg",
            "Gymnasium Hoheluft",
            "Gymnasium Kaiser-Friedrich-Ufer",
            "Gymnasium Klosterschule",
            "Gymnasium Lerchenfeld",
            "Gymnasium Lohbrügge",
            "Gymnasium Marienthal",
            "Gymnasium Meiendorf",
            "Gymnasium Oberalster",
            "Gymnasium Ohlstedt",
            "Gymnasium Ohmoor",
            "Gymnasium Oldenfelde",
            "Gymnasium Osterbek",
            "Gymnasium Rahlstedt",
            "Gymnasium Rissen",
            "Gymnasium Süderelbe",
            "Hansa-Gymnasium Bergedorf",
            "Hansa-Kolleg",
            "Heinrich-Heine-Gymnasium",
            "Heisenberg-Gymnasium",
            "Helene-Lange-Gymnasium",
            "Helmut-Schmidt-Gymnasium",
            "Immanuel-Kant-Gymnasium",
            "Jenisch-Gymnasium",
            "Johannes-Brahms-Gymnasium",
            "Kurt-Körber-Gymnasium",
            "Lise-Meitner-Gymnasium",
            "Luisen-Gymnasium Bergedorf",
            "Margaretha-Rothe-Gymnasium",
            "Marion Dönhoff Gymnasium",
            "Privates Abendgymnasium Brecht",
            "Sankt-Ansgar-Schule",
            "Sophie-Barat-Schule",
            "Studienkolleg für ausländische Studierende",
            "Walddörfer-Gymnasium",
            "Wichern-Schule (Gymnasium)",
            "Erich-Klausener-Gymnasium ",
            "Priv. Gymnasium der Ursulinen ",
            "Are-Gymnasium ",
            "Peter-Joerres-Gymnasium ",
            "Priv. Gymnasium Nonnenwerth  ",
            "Rhein-Gymnasium  ",
            "Westerwald-Gymnasium  ",
            "Freiherr-vom-Stein Gymnasium  ",
            "Kopernikus-Gymnasium  ",
            "Staatliches Aufbaugymnasium  ",
            "Gymnasium am Römerkastell ",
            "Elisabeth-Langgässer-Gymnasium ",
            "Werner-Heisenberg-Gymnasium  ",
            "Hannah-Arendt-Gymnasium ",
            "Gymnasium an der Stadtmauer  ",
            "Lina-Hilger-Gymnasium ",
            "Emanuel-Felke-Gymnasium ",
            "Alfred-Delp-Schule  ",
            "Gymnasium Kirn ",
            "Nikolaus-von-Kues-Gymnasium  ",
            "Gymnasium Traben-Trarbach ",
            "Peter-Wust-Gymnasium  ",
            "Gymnasium Birkenfeld  ",
            "Gymnasium an der Heinzenwies  ",
            "Martin-von-Cochem-Gymnasium  ",
            "Priv. Gymnasium  ",
            "Nordpfalzgymnasium  ",
            "Wilhelm-Erb-Gymnasium ",
            "Privates St.-Josef-Gymnasium  ",
            "St.-Willibrord-Gymnasium ",
            "Priv. Gymnasium St. Matthias  ",
            "Eifel-Gymnasium  ",
            "Regino-Gymnasium  ",
            "Priv. Vinzenz-von-Paul- ",
            "Albert-Einstein-Gymnasium ",
            "Europa Gymnasium  ",
            "St.-Franziskus-Gymnasium ",
            "Albert-Schweitzer-Gymnasium  ",
            "Gymnasium am Rittersberg ",
            "Burggymnasium ",
            "Hohenstaufen-Gymnasium ",
            "Sickingen-Gymnasium  ",
            "Gymnasium Ramstein-Miesenbach ",
            "Bischöfliches Cusanus- ",
            "Eichendorff-Gymnasium ",
            "Görres-Gymnasium  ",
            "Gymnasium auf der Karthause  ",
            "Hilda-Gymnasium  ",
            "Max-von-Laue-Gymnasium ",
            "Gymnasium Kusel  ",
            "Veldenz Gymnasium  ",
            "Priv. Maria-Ward-Gymnasium ",
            "Max-Slevogt-Gymnasium ",
            "Otto-Hahn-Gymnasium  ",
            "Carl-Bosch-Gymnasium  ",
            "Geschwister-Scholl-Gymnasium  ",
            "Max-Planck-Gymnasium  ",
            "Theodor-Heuss-Gymnasium ",
            "Wilhelm-von-Humboldt-Gymnasium ",
            "Priv. Bischöfl. Willigis- ",
            "Private Maria-Ward-Schule ",
            "Rabanus-Maurus-Gymnasium ",
            "Gymnasium am ",
            "Otto-Schott Gymnasium ",
            "Priv. Theresianum-Gymnasium  ",
            "Private Hildegardis-Schule ",
            "Stefan-George-Gymnasium ",
            "Gymnasium Nackenheim  ",
            "Bertha-von-Suttner-Gymnasium  ",
            "Kurfürst-Salentin-Gymnasium  ",
            "Wilhelm-Remy-Gymnasium ",
            "Megina-Gymnasium  ",
            "Gymnasium Mülheim-Kärlich ",
            "Kurfürst-Balduin-Gymnasium ",
            "Priv. Schönstätter  ",
            "Käthe-Kollwitz-Gymnasium ",
            "Kurfürst-Ruprecht-Gymnasium  ",
            "Martinus-Gymnasium  ",
            "Wiedtal-Gymnasium  ",
            "Rhein-Wied-Gymnasium  ",
            "Immanuel-Kant-Gymnasium ",
            "Hugo-Ball-Gymnasium  ",
            "Kant-Gymnasium ",
            "Ausonius-Gymnasium  ",
            "Herzog-Johann-Gymnasium ",
            "Goethe-Gymnasium  ",
            "Sophie-Hedwig-Gymnasium ",
            "Johannes-Gymnasium  ",
            "Marion-Dönhoff-Gymnasium ",
            "Wilhelm-Hofmann-Gymnasium ",
            "Edith-Stein-Gymnasium ",
            "Priv. Nikolaus-von-Weis- ",
            "Friedrich-Magnus-Schwerd- ",
            "Gymnasium am Kaiserdom ",
            "Hans-Purrmann-Gymnasium ",
            "Gymnasium im Alfred-Grosser-  ",
            "Kooperative Gesamtschule ",
            "Otfried-von-Weißenburg- ",
            "Bischöfliches ",
            "Auguste-Viktoria-Gymnasium ",
            "Friedrich-Spee-Gymnasium ",
            "Humboldt-Gymnasium  ",
            "Max-Planck-Gymnasium  ",
            "Gymnasium Hermeskeil  ",
            "Gymnasium Konz ",
            "Gymnasium Saarburg  ",
            "Dietrich-Bonhoeffer-Gymnasium ",
            "Stefan-Andres-Gymnasium ",
            "Geschwister-Scholl-Gymnasium  ",
            "Thomas-Morus-Gymnasium ",
            "St. Matthias-Gymnasium ",
            "Evangelisches ",
            "Gymnasium im Kannenbäckerland ",
            "Mons-Tabor-Gymnasium  ",
            "Priv. Gymnasium  ",
            "Konrad-Adenauer-Gymnasium ",
            "Privates Gymnasium  ",
            "Rudi-Stephan-Gymnasium ",
            "Eleonoren-Gymnasium  ",
            "Helmholtz-Gymnasium  ",
            "Hofenfels-Gymnasium  ",
            "Altes Gymnasium ",
            "Goethe-Schule ",
            "Hebbelschule Europaschule",
            "Humboldt-Schule ",
            "Kieler Gelehrtenschule Altsprachliches Gymnasium",
            "Max-Planck-Schule ",
            "Ricarda-Huch-Schule ",
            "Hans-Geiger Gymnasium ",
            "Gymnasium Wellingdorf ",
            "Thor-Heyerdahl-Gymnasium im Bildungszentrum Mettenhof",
            "Gymnasium Elmschenhagen ",
            "Carl-Jacob-Burckhardt-Gymnasium UNESCO-Projektschule",
            "Ernestinenschule ",
            "Johanneum zu Lübeck Gymnasium für Jungen und Mädchen",
            "Katharineum zu Lübeck ",
            "Thomas-Mann-Schule Europaschule",
            "Holstenschule Europaschule",
            "Immanuel-Kant-Schule ",
            "Klaus-Groth-Schule ",
            "Alexander-von-Humboldt-Schule ",
            "Schule am Meer Europaschule",
            "Werner-Heisenberg-Gymnasium ",
            "Gymnasium Marne Europaschule",
            "Meldorfer Gelehrtenschule ",
            "Gymnasium Heide-Ost Europaschule",
            "Gymnasium Brunsbüttel ",
            "Otto-Hahn-Gymnasium Europaschule",
            "Lauenburgische Gelehrtenschule ",
            "Gymnasium Schwarzenbek Europaschule",
            "Theodor-Storm-Schule ",
            "Friedrich-Paulsen-Schule Gymnasium des Amtes Südtondern",
            "Nordseeschule Gymnasium mit Regionalschulteil Europaschule",
            "Schulzentrum Sylt Gymnasium und Regionalschule Sylt",
            "Eilun Feer Skuul Gymnasium und Regionalschule",
            "Carl-Maria-von-Weber-Schule Europaschule",
            "Johann-Heinrich-Voß-Schule ",
            "Leibniz-Gymnasium ",
            "Gymnasium am Mühlenberg ",
            "Bismarckschule ",
            "Elsa-Brändström-Schule ",
            "Theodor-Heuss-Schule ",
            "Dietrich-Bonhoeffer-Gymnasium ",
            "Ludwig-Meyn-Gymnasium ",
            "Johann-Rist-Gymnasium ",
            "Carl-Friedrich-von-Weizsäcker-Gymnasium Barmstedt/Rantzau",
            "Gymnasium Schenefeld ",
            "Gymnasium Lütjenburg im Hoffmann-von-Fallersleben-Schulzentrum",
            "Friedrich-Schiller-Gymnasium ",
            "Heinrich-Heine-Gymnasium ",
            "Jungmannschule ",
            "Helene-Lange-Gymnasium ",
            "Herderschule Europaschule",
            "Gymnasium Altenholz ",
            "Gymnasium Kronshagen ",
            "Gymnasium Kronwerk ",
            "Schule Hohe Geest Gymnasium i.E. mit Regionalschulteil des Schulverbandes Hohenwestedt",
            "Klaus-Harms-Schule ",
            "Bernstorff-Gymnasium Satrup Europaschule",
            "Domschule ",
            "Jürgen-Fuhlendorf-Schule ",
            "Dahlmannschule ",
            "Gymnasium Kaltenkirchen ",
            "Städtisches Gymnasium ",
            "Lise-Meitner-Gymnasium ",
            "Detlefsengymnasium ",
            "Auguste Viktoria Schule ",
            "Stormarnschule ",
            "Emil-von-Behring-Gymnasium Europaschule",
            "Sachsenwaldschule ",
            "Gymnasium Glinde"
        };
    }
}